# -*- coding: utf-8 -*-
"""SIgnal_1ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pxP0sV808E0HPGVXTmLD0G66I8pKrRq8
"""

# Importing all the libraries
import numpy as np
import matplotlib.pyplot as plt

# The x coordinates of the given points
X = [3,-2,8]
# The x coordinates of the given points
Y = [0,-2,2]

# Plotting the given points
plt.scatter(X,Y,label = 'Points')
plt.plot(X,Y,color = 'red',label = 'line')

# Naming the x axis
plt.xlabel('x - axis')
# Naming the y axis
plt.ylabel('y - axis')

# Function to show the plot
plt.legend()
plt.grid(True)
plt.show()

# Conclusion
print("Hence, the points are collinear")