# -*- coding: utf-8 -*-
"""GATE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UXU88L-LKMQ4ULrxWG8_RQLDQak9FGZ4
"""

# Importing all the libraries
import numpy as np
import matplotlib.pyplot as plt

# The X cooridnates of the points
X = [-3,-2,-1,0,1,2,3]
# The Y coordinates of the points
Y = [0,0,0,1,3,1,0]
# The x coordiantes of the shifted points
X_t = [-3,-2,-1,0,1,2]
# The y coordinates of the shifted points
Y_t = Y[1:]

# Plotting the original graph
plt.scatter(X,Y,label = 'Points')
plt.plot(X,Y,color = 'red',label = 'line')
# Plotting the shifted graph
plt.scatter(X_t,Y_t,label = 'ShiftedPoints')
plt.plot(X_t,Y_t,color = 'green',label = 'shiftedline')
# Naming the x axis
plt.xlabel('t')
# Naming the y axis
plt.ylabel('y(t)=x(t+1)')
plt.grid(True)
# Function to show the plot
plt.legend()
plt.show()