# -*- coding: utf-8 -*-
"""Quiz_1_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_iRd6ubs0uuDFvsv96DSAn6OXg6aLD4p
"""

import matplotlib.pyplot as plt
import numpy as np

n = np.linspace(0,25,50,endpoint=True)

x = np.e**(1j*np.pi*n/6)

plt.plot(n,x)
plt.grid()
plt.xlabel("n")
plt.ylabel("(x[n])")

plt.show()

import matplotlib.pyplot as plt
import numpy as np

n = np.linspace(0,25,50,endpoint=True)

x = np.e**(1j*3*np.pi*n/4)

plt.plot(n,x)
plt.grid()
plt.xlabel("n")
plt.ylabel("(x[n])")

plt.show()

import matplotlib.pyplot as plt
import numpy as np

n = np.linspace(0,25,50,endpoint=True)

x = (np.sin(np.pi*n/5))/(np.pi*n)

plt.plot(n,x)
plt.grid()
plt.xlabel("n")
plt.ylabel("(x[n])")

plt.show()