# -*- coding: utf-8 -*-
"""Linear_form.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MY-3NKRlOPEAGPGO2fKfFnoFxzZlQaw-
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(-5,5,100)
y = 5*x-3
X = np.array([0,-3,5])
Y = np.array([-3,-18,22])
plt.plot(X[0],Y[0],'o',label='x=0')
plt.text(X[0] + (0.3), Y[0] - (1.2) , 'x=0')
plt.plot(X[1],Y[1],'o',label='x=-3')
plt.text(X[1] + (0.1), Y[1] - (1.2) , 'x=-3')
plt.plot(X[2],Y[2],'o',label='x=5')
plt.text(X[2] -(1), Y[2] - (1) , 'x=5')
plt.plot(x,y,label='f(x)')
plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() 
plt.show()