# -*- coding: utf-8 -*-
"""Code_Matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FYmI3RTA0AY_7k1cD4xOJ2-NZ8rlQZtl
"""

# Importing numpy library  
import numpy as np

# Framing the matrix A and B
matrix_A = np.array([[1,2,3],[4,5,6]])
matrix_B = np.array([[-7,-8,-9],[2,4,6]])

# Taking the transpose of A
matrix_AT = matrix_A.T

# Using least square method
# Multipling matrix B and A.T
BA_T = (matrix_B @ matrix_AT)
# Multipling matrix A and A.T
AA_T = (matrix_A @ matrix_AT)
# Taking the inverse of AA_T matrix
AA_T = np.linalg.inv(AA_T)
# Finding the unknow matrix X
matrix_X = (BA_T @ AA_T)

# Printing the expected output
print(matrix_X)

# Output
# [[ 1. -2.]
# [ 2.  0.]]