# -*- coding: utf-8 -*-
"""Matrix_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gz_oPyK1BuotTtni0PNM3BoC-5LQkuqR
"""

# Importing numpy library  
import numpy as np

# Framing the coefficient matrix for 1st part
coefficient_matrix = np.array([
    [1, 4],
    [2, 5]
])

# Framing the value matrix for 1st part
value_matrix = np.array([-7, -8])

# Finding the result of 1st part
result = np.linalg.solve(coefficient_matrix, value_matrix)

# Printing the result of 1st part
print(result)

# output
# [ 1. -2.]

# Framing the coefficient matrix for 2nd part
coefficient_matrix_2 = np.array([
    [1, 4],
    [2, 5]
])

# Framing the value matrix for 2nd part
value_matrix_2 = np.array([2, 4])

# Finding the result of 2nd part
result_2 = np.linalg.solve(coefficient_matrix_2, value_matrix_2)

# Printing the result of 2nd part
print(result_2)

# output
# [2. 0.]