# -*- coding: utf-8 -*-
"""Code_Matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FYmI3RTA0AY_7k1cD4xOJ2-NZ8rlQZtl
"""

# Importing numpy library  
import numpy as np

# Framing the matrix A and B
matrix_A = np.array([[1,2,3],[4,5,6]])
matrix_B = np.array([[-7,-8,-9],[2,4,6]])

# Taking the transpose of A
matrix_AT = matrix_A.T

# Using least square method
matrix_X = np.dot(np.dot(matrix_B,matrix_AT),np.linalg.inv(np.dot(matrix_A,matrix_AT)))

# Printing the expected output
print(matrix_X)

# Output
# [[ 1. -2.]
# [ 2.  0.]]