# -*- coding: utf-8 -*-
"""Matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bJwIoH96tZnR5atmX82OmOSTCMn6_Zpn
"""

# Importing all the libraries
import matplotlib.pyplot as plt
import numpy as np

# Plotting the equation of the first line
a1 = -7 -4*b
plt.plot(b, a1, 'r', label = 'a+4b = -7')

# Plotting the equation of the second line
a2 = (-7/2) - (5*b/2)
plt.plot(b, a2, 'c',label = '2a+5b = -8')

# Implementing few more plotting functions
plt.title('Intersection of two straight lines', fontsize=10)
plt.annotate("solution (1,-2)", (1,-2))
plt.xlabel('x-axis');plt.ylabel('y-axis')
plt.legend(loc='best')
plt.grid()

# Plotting the equation of the third line
c1 = 2 -4*d
plt.plot(d, c1, 'r', label = 'c+4d = 2')

# Plotting the equation of the fourth line
c2 = 2 - (5*d/2)
plt.plot(d, c2, 'c',label = '2c+5d = 4')

# Implementing few more plotting functions
plt.title('Intersection of two straight lines', fontsize=10)
plt.annotate("solution (2,0)", (2,0))
plt.xlabel('x-axis');plt.ylabel('y-axis')
plt.legend(loc='best')
plt.grid()