# -*- coding: utf-8 -*-
"""Construction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nT86-dn3RB7GFX72tB9vmd-5ZDnaeq2u
"""

# Importing all the libraries
import numpy as np
import matplotlib.pyplot as plt

# Setting up the points
Q = np.array([2.5,4.33]) 
O = np.array([0,0]) 
R = np.array([2.5,-4.33]) 
P = np.array([10,0]) 

# Generating the line points
def line_gen(X,Y):
  len =10
  x = np.zeros((2,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = X + lam_1[i]*(Y-X)
    x[:,i]= temp1.T
  return x

# Calling the function of lin_gen 
x_OQ = line_gen(O,Q)
x_QP = line_gen(Q,P)
x_OP = line_gen(O,P)
x_PR = line_gen(R,P)

# Plotting all the lines generated
plt.plot(x_OQ[0,:],x_OQ[1,:],label='$OQ$')
plt.plot(x_QP[0,:],x_QP[1,:],label='$QP$')
plt.plot(x_OP[0,:],x_OP[1,:],label='$OP$')
plt.plot(x_PR[0,:],x_PR[1,:],label='$PR$')

# Putting up labels
plt.plot(O[0], O[1], 'o')
plt.text(O[0] + (0.1), O[1] - (0.5) , 'O')
plt.plot(Q[0], Q[1], 'o')
plt.text(Q[0] * (1 + 0.2), Q[1] * (1) , 'Q')
plt.plot(P[0], P[1], 'o')
plt.text(P[0] * (1 + 0.03), P[1] * (1 - 0.1) , 'P')
plt.plot(R[0], R[1], 'o')
plt.text(R[0] * (1 - 0.2), R[1] * (1) , 'R')

# Ploting the circle
theta = np.linspace(0,2*np.pi,50)
x = 5*np.cos(theta)
y = 5*np.sin(theta)
plt.plot(x,y)
plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()